- name: Play 1
  hosts: all
  vars:
    # - commit_id: "{{ commit_id | default('default_env') }}"
    - proj_name: "{{ proj_name | default('default_project') }}"
    - u_repo_docker: "{{ u_repo_docker | default('fajarsujai') }}"
    - proj_port: "{{ proj_port | default('8001') }}"
    - proj_env: "{{ proj_env | default('develop') }}"
  tasks:
    - name: Get commit_id by git
      command: git log --pretty=format:%h -1
      register: commit_id
      # when: commit_id | regex_search("^[a-zA-Z0-9]+$")

    - name: Set commit_id to variable
      set_fact:
        proj_tag: "{{ commit_id.stdout }}"
      debug:
        msg: "{{ proj_tag }}"
      # when: commit_id | regex_search("^[a-zA-Z0-9]+$")

    # - name: Run if env develop
    #   become: true
    #   become_user: root
    #   block:
    #     - docker_login:
    #         username: "fajarsujai"
    #         password: "SeptemberRain$10"
    #     - command: "docker build -t {{u_repo_docker}}/{{proj_name}}:{{commit_id}} --build-arg BRANCH={{proj_env}} --build-arg PORT={{proj_port}}  ."
    #       register: v_docker_1
    #     - command: "docker push {{u_repo_docker}}/{{proj_name}}:{{commit_id}}"
    #       register: v_docker_2
    #     - debug:
    #         msg: 
    #           - "Docker build"
    #           - '{{ v_docker_1.stdout_lines }}'
    #           - "Docker push"
    #           - '{{ v_docker_2.stdout_lines }}'
    #   when: commit_id | regex_search("^[a-zA-Z0-9]+$")
      
    # - name: Get tag_rc_id by git
    #   command: git describe --tags --abbrev=0
    #   register: tag_rc_id
    #   when: tag_rc_id | regex_search("^rc\-[0-9]+\.[0-9]+\.[0-9]+$")

    # - name: Set tag_rc_id to variable
    #   set_fact:
    #     proj_tag: "{{ tag_rc_id.stdout }}"
    #   when: tag_rc_id | regex_search("^rc\-[0-9]+\.[0-9]+\.[0-9]+$")
    
    # - name: Run if env staging
    #   become: true
    #   become_user: root
    #   block:
    #     - 
    #     - docker_login:
    #         username: "fajarsujai"
    #         password: "SeptemberRain$10"
    #     - command: "docker build -t {{u_repo_docker}}/{{proj_name}}:{{commit_id}} --build-arg BRANCH={{proj_env}} --build-arg PORT={{proj_port}}  ."
    #       register: v_docker_1
    #     - command: "docker push {{u_repo_docker}}/{{proj_name}}:{{commit_id}}"
    #       register: v_docker_2
    #     - debug:
    #         msg: 
    #           - "Docker build"
    #           - '{{ v_docker_1.stdout_lines }}'
    #           - "Docker push"
    #           - '{{ v_docker_2.stdout_lines }}'
    #   when: commit_id | regex_search("^rc\-[0-9]+\.[0-9]+\.[0-9]+$")

    # - name: Run if env production
    #   become: true
    #   become_user: root
    #   block:
    #     - docker_login:
    #         username: "fajarsujai"
    #         password: "SeptemberRain$10"
    #     - command: "docker build -t {{u_repo_docker}}/{{proj_name}}:{{commit_id}} --build-arg BRANCH={{proj_env}} --build-arg PORT={{proj_port}}  ."
    #       register: v_docker_1
    #     - command: "docker push {{u_repo_docker}}/{{proj_name}}:{{commit_id}}"
    #       register: v_docker_2
    #     - debug:
    #         msg: 
    #           - "Docker build"
    #           - '{{ v_docker_1.stdout_lines }}'
    #           - "Docker push"
    #           - '{{ v_docker_2.stdout_lines }}'
    #   when: commit_id | regex_search("^v[0-9]+\.[0-9]+\.[0-9]+$")
    
    