- name: Play 1
  hosts: all
  tasks:
    - name: Get commit_id by git
      command: git log --pretty=format:%h -1
      register: commit_id
      when: proj_env == 'develop'

    - name: Set commit_id to variable
      set_fact:
        proj_tag: "{{ commit_id.stdout }}"
    - debug:
        msg: "{{ proj_tag }}"
      when: proj_env == 'develop'

    - name: Run if env develop
      become: true
      become_user: root
      block:
        - docker_login:
            username: "fajarsujai"
            password: "SeptemberRain$10"
        - command: "docker build -t {{u_repo_docker}}/{{proj_name}}:{{commit_id}} --build-arg BRANCH={{proj_env}} --build-arg PORT={{proj_port}}  ."
          register: v_docker_1
        - command: "docker push {{u_repo_docker}}/{{proj_name}}:{{commit_id}}"
          register: v_docker_2
        - debug:
            msg: 
              - "Docker build"
              - '{{ v_docker_1.stdout_lines }}'
              - "Docker push"
              - '{{ v_docker_2.stdout_lines }}'
      when: commit_id | regex_search("^[a-zA-Z0-9]+$")
      
    - name: Get commit_id by git
      command: git describe --abbrev=0 --tags --match "rc*"
      register: commit_id
      when: proj_env == 'staging'

    - name: Set commit_id to variable
      set_fact:
        proj_tag: "{{ commit_id.stdout }}"
    - debug:
        msg: "{{ proj_tag }}"
      when: proj_env == 'staging'
    
    - name: Run if env staging
      become: true
      become_user: root
      block:
        - 
        - docker_login:
            username: "fajarsujai"
            password: "SeptemberRain$10"
        - command: "docker build -t {{u_repo_docker}}/{{proj_name}}:{{commit_id}} --build-arg BRANCH={{proj_env}} --build-arg PORT={{proj_port}}  ."
          register: v_docker_1
        - command: "docker push {{u_repo_docker}}/{{proj_name}}:{{commit_id}}"
          register: v_docker_2
        - debug:
            msg: 
              - "Docker build"
              - '{{ v_docker_1.stdout_lines }}'
              - "Docker push"
              - '{{ v_docker_2.stdout_lines }}'
      when: commit_id | regex_search("^rc\-[0-9]+\.[0-9]+\.[0-9]+$")

    - name: Get commit_id by git
      command: git describe --abbrev=0 --tags --match "v*"
      register: commit_id
      when: proj_env == 'production'

    - name: Set commit_id to variable
      set_fact:
        proj_tag: "{{ commit_id.stdout }}"
    - debug:
        msg: "{{ proj_tag }}"
      when: proj_env == 'production'

    - name: Run if env production
      become: true
      become_user: root
      block:
        - docker_login:
            username: "fajarsujai"
            password: "SeptemberRain$10"
        - command: "docker build -t {{u_repo_docker}}/{{proj_name}}:{{commit_id}} --build-arg BRANCH={{proj_env}} --build-arg PORT={{proj_port}}  ."
          register: v_docker_1
        - command: "docker push {{u_repo_docker}}/{{proj_name}}:{{commit_id}}"
          register: v_docker_2
        - debug:
            msg: 
              - "Docker build"
              - '{{ v_docker_1.stdout_lines }}'
              - "Docker push"
              - '{{ v_docker_2.stdout_lines }}'
      when: commit_id | regex_search("^v[0-9]+\.[0-9]+\.[0-9]+$")
    
    