regex_search("^[a-zA-Z0-9]+$")

regex_search("^rc\-[0-9]+\.[0-9]+\.[0-9]+$")

regex_search("^v[0-9]+\.[0-9]+\.[0-9]+$")

- name: Play 1
  hosts: all
  tasks:
    #Mengambil nama project
    - name: Get proj_name by git
      ansible.builtin.shell:
        cmd: basename $(pwd -P)
      register: proj_name
      
    - name: Set proj_name to variable
      set_fact:
        proj_name: "{{ proj_name.stdout }}"
    - debug:
        msg: "{{ proj_name }}"
    #End Mengambil nama project

    #Mengambil tag repo develop
    - name: Get tag_repo_dev by git
      command: git log --pretty=format:%h -1
      register: tag_repo_dev
      when: proj_env == 'develop' or proj_env | regex_search("^[a-zA-Z0-9]+$")

    - name: Set tag_repo_dev to variable
      set_fact:
        proj_tag: "{{ tag_repo_dev.stdout }}"
    - debug:
        msg: "{{ proj_tag }}"
      when: proj_env == 'develop' or proj_tag | regex_search("^[a-zA-Z0-9]+$")
    #END Mengambil tag repo develop

    #Build & push images to docker (develop)
    - name: Run if env develop
      become: true
      become_user: root
      block:
        - docker_login:
            username: "fajarsujai"
            password: "SeptemberRain$10"
        - command: "docker build -t {{u_repo_docker}}/{{proj_name}}:{{proj_tag}} --build-arg BRANCH={{proj_env}} --build-arg PORT={{proj_port}}  ."
          register: v_docker_1
        - command: "docker push {{u_repo_docker}}/{{proj_name}}:{{proj_tag}}"
          register: v_docker_2
        - debug:
            msg: 
              - "Docker build"
              - '{{ v_docker_1.stdout_lines }}'
              - "Docker push"
              - '{{ v_docker_2.stdout_lines }}'
      when: proj_env == 'develop' or proj_env | regex_search("^[a-zA-Z0-9]+$")
    #End Build & push images to docker (develop)

      #Mengambil tag repo staging
    - name: Get tag_repo_sta by git
      command: git describe --abbrev=0 --tags --match "rc*"
      register: tag_repo_sta
      when: proj_env == 'staging' or proj_tag | regex_search("^rc\-[0-9]+\.[0-9]+\.[0-9]+$")

    - name: Set tag_repo_sta to variable
      set_fact:
        proj_tag: "{{ tag_repo_sta.stdout }}"
    - debug:
        msg: "{{ proj_tag }}"
      when: proj_env == 'staging' or proj_tag | regex_search("^rc\-[0-9]+\.[0-9]+\.[0-9]+$")
      #End mengambil tag repo staging

    #Build & push images to docker (staging)
    - name: Run if env staging
      become: true
      become_user: root
      block:
        - 
        - docker_login:
            username: "fajarsujai"
            password: "SeptemberRain$10"
        - command: "docker build -t {{u_repo_docker}}/{{proj_name}}:{{proj_tag}} --build-arg BRANCH={{proj_env}} --build-arg PORT={{proj_port}}  ."
          register: v_docker_1
        - command: "docker push {{u_repo_docker}}/{{proj_name}}:{{proj_tag}}"
          register: v_docker_2
        - debug:
            msg: 
              - "Docker build"
              - '{{ v_docker_1.stdout_lines }}'
              - "Docker push"
              - '{{ v_docker_2.stdout_lines }}'
      when: proj_env == 'staging' or proj_tag | regex_search("^rc\-[0-9]+\.[0-9]+\.[0-9]+$")
      #End build & push images to docker (staging)
 

    #Mengambil tag repo production
    - name: Get tag_repo_prod by git
      command: git describe --abbrev=0 --tags --match "v*"
      register: tag_repo_prod
      when: proj_env == 'production' or proj_tag | regex_search("^v[0-9]+\.[0-9]+\.[0-9]+$")

    - name: Set tag_repo_prod to variable
      set_fact:
        proj_tag: "{{ tag_repo_prod.stdout }}"
    - debug:
        msg: "{{ proj_tag }}"
      when: proj_env == 'production' or proj_tag | regex_search("^v[0-9]+\.[0-9]+\.[0-9]+$")
    #End Mengambil tag repo production
    
    #Build & push images to docker (production)
    - name: Run if env production
      become: true
      become_user: root
      block:
        - docker_login:
            username: "fajarsujai"
            password: "SeptemberRain$10"
        - command: "docker build -t {{u_repo_docker}}/{{proj_name}}:{{proj_tag}} --build-arg BRANCH={{proj_env}} --build-arg PORT={{proj_port}}  ."
          register: v_docker_1
        - command: "docker push {{u_repo_docker}}/{{proj_name}}:{{proj_tag}}"
          register: v_docker_2
        - debug:
            msg: 
              - "Docker build"
              - '{{ v_docker_1.stdout_lines }}'
              - "Docker push"
              - '{{ v_docker_2.stdout_lines }}'
      when: proj_env == 'production' or proj_tag | regex_search("^v[0-9]+\.[0-9]+\.[0-9]+$")
      #End Build & push images to docker (production)
    
    